# docker-compose.yml
version: '3.9'

services:
  web:
    build: .
    environment:
      - GREETING=Hello, inalabgroup!
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
